apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-score-config
  namespace: credit-score
data:
  mlflow_tracking_uri: "http://mlflow:5000"
  mlflow_model_name: "lightgbm"
  mlflow_experiment_id: "194323661774503133"
