apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-score-config
  namespace: credit-score
data:
  mlflow_tracking_uri: "http://mlflow-service:5000"
  mlflow_model_name: "credit_score_serving"
  MLFLOW_MODEL_ALIAS: "production"
  MLFLOW_EXPERIMENT_NAME: "credit-score-v1"
