apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: credit-score-artifacts-pvc
  namespace: credit-score
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
